src/config/urls.py
from django.contrib import admin
from django.urls import path, include

from students.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

src/students/urls.py
from django.urls import path

from students.views import (
    get_all_students,
    CreateStudentView,
    UpdateStudentView,
    delete_student,
    test,
    search_history,
    Login,
    Logout,
    Registration,
    send_test_email,
    ActivateUser,
)

app_name = "students"

urlpatterns = [
    path("", get_all_students, name="all_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:uuid>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", delete_student, name="delete_student"),
    path("search-history/", search_history, name="search_history"),
    path("test/", test, name="test_view"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("send-test-email/", send_test_email, name="test_send_email"),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# www.facebook.com/students/ - all
# www.facebook.com/students/create/ - create
# www.facebook.com/students/15 - get one element
# www.facebook.com/students/update/15 - update
# www.facebook.com/students/delete/15 - update

src/templates/index.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Cover Template · Bootstrap v5.2</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossorigin="anonymous">
    <link rel="canonical"
          href="https://getbootstrap.com/docs/5.2/examples/cover/">


    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <a href="{% url 'index' %}">
                <h3 class="float-md-start mb-0">
                    LMS</h3>
            </a>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link fw-bold py-1 px-0 active"
                   aria-current="page"
                   href="{% url 'index' %}">Home</a>

                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'students:all_students' %}">Students list</a>

                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'students:create_student' %}">Create</a>
                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'students:search_history' %}">Search
                    history</a>

                <a href="#"
                   class="nav-link fw-bold py-1 px-0 d-block link-dark text-decoration-none dropdown-toggle"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="mdo"
                         class="rounded-circle" width="32" height="32">
                </a>
                {% if user.is_authenticated %}
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item"
                               href="">{{ user.username|title }}</a></li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        {% if user.is_staff %}
                            <li><a class="dropdown-item"
                                   href="{% url 'admin:index' %}">Admin
                                page</a>
                            </li>
                        {% endif %}
                        <li><a class="dropdown-item" href="#">Change
                            password</a>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item"
                               href="{% url 'students:logout' %}">Sign out</a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item"
                               href="{% url 'students:login' %}">Login</a></li>
                        <li><a class="dropdown-item"
                               href="{% url 'students:registration' %}">Registration</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Reset
                            password</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Gmail</a></li>
                        <li><a class="dropdown-item" href="#">Facebook</a></li>
                    </ul>
                {% endif %}
            </nav>
        </div>
    </header>

    <main class="px-3">
        {% block content %}
            <h1>Cover your page.</h1>
            <p class="lead">Cover is a one-page template for building simple
                and
                beautiful home pages. Download, edit the text, and add your own
                fullscreen background photo to make it your own.</p>
            <p class="lead">
                {% for i in key %}
                    <p>{{ i }}</p>
                {% endfor %}
            <form method="GET" action="{% url 'students:all_students' %}">
                <div class="input-group mb-3">
                    <input type="text" class="form-control"
                           placeholder="Search students"
                           name="search_text"
                           aria-label="Search students"
                           aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="submit"
                            id="button-addon2">Search
                    </button>
                </div>
            </form>

            {#                <a href="#"#}
            {#                   class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn#}
            {#                    more</a>#}
            {#                <img src="{% static 'img/1.jpg' %}" alt="no image">#}
            </p>
        {% endblock %}
    </main>

    <footer class="mt-auto text-white-50">
        <p>Cover template for <a href="https://getbootstrap.com/"
                                 class="text-white">Bootstrap</a>, by <a
                href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
    </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>
</html>

src/templates/search_history.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        {% for key, value in search_logs.items %}
            <p>{{ key }} {{ value }}</p>
        {% endfor %}
    </div>
{% endblock content %}

src/templates/students_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create
            </button>
        </form>
    </div>
{% endblock content %}

src/templates/students_list.html
{% extends "index.html" %}

{% block content %}
    {#    <form>#}
    {#          <label for="first_name">First name:</label><br>#}
    {#          <input type="text" name="first_name"><br>#}
    {##}
    {#          <label for="last_name">Last name:</label><br>#}
    {#          <input type="text" name="last_name"><br><br>#}
    {##}
    {#          <label for="search_text">Search text:</label><br>#}
    {#          <input type="text" name="search_text"><br><br>#}
    {##}
    {#          <button type="submit" value="Submit">Submit</button>#}
    {#</form>#}
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">#id</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Birth date</th>
            <th scope="col">Age</th>
            <th scope="col">Grade</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for student in students %}
            <tr>
                <th scope="row">{{ student.pk }}</th>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                {% if student.birth_date %}
                    <td>{{ student.birth_date }}</td>
                    <td>{{ student.age }}</td>
                {% else %}
                    <td>Undefined</td>
                    <td>Undefined</td>
                {% endif %}
                <td>{{ student.grade }}</td>
                <td><a type="button" class="btn btn-warning"
                       href="{% url 'students:update_student' student.pk %}">Edit</a>
                </td>
                <td><a type="button" class="btn btn-danger"
                       href="{% url 'students:delete_student' student.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/templates/students_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update">Update
            </button>
        </form>
    </div>
{% endblock content %}